#!/bin/bash
# stored in /usr/local/bin

TEXT_RESET='\e[0m'
TEXT_YELLOW='\e[0;33m'
TEXT_RED_B='\e[1;31m'

echo -e $TEXT_YELLOW
echo "\n# running apt updates...\n"
echo -e $TEXT_RESET
sudo apt update -y
sudo apt upgrade -y
sudo apt full-upgrade -y


#echo -e $TEXT_YELLOW
#echo "\n# running apt-get updates...\n"
#echo -e $TEXT_RESET
#sudo apt-get update -y
#sudo apt-get full-upgrade -y

echo -e $TEXT_YELLOW
echo "\n# cleaning...\n"
echo -e $TEXT_RESET
sudo apt autoremove
sudo apt-get clean
